slim selAndNeut.in > sanOut01
slim selAndNeut.in > sanOut02
slim selAndNeut.in > sanOut03
slim selAndNeut.in > sanOut04
slim selAndNeut.in > sanOut05
slim selAndNeut.in > sanOut06
slim selAndNeut.in > sanOut07
slim selAndNeut.in > sanOut08
slim selAndNeut.in > sanOut09
slim selAndNeut.in > sanOut10
slim selAndNeut.in > sanOut11
slim selAndNeut.in > sanOut12
slim selAndNeut.in > sanOut13
slim selAndNeut.in > sanOut14
slim selAndNeut.in > sanOut15
slim selAndNeut.in > sanOut16
slim selAndNeut.in > sanOut17
slim selAndNeut.in > sanOut18
slim selAndNeut.in > sanOut19
slim selAndNeut.in > sanOut20
slim selAndNeut.in > sanOut21
slim selAndNeut.in > sanOut22
slim selAndNeut.in > sanOut23
slim selAndNeut.in > sanOut24
slim selAndNeut.in > sanOut25
slim selAndNeut.in > sanOut26
slim selAndNeut.in > sanOut27
slim selAndNeut.in > sanOut28
slim selAndNeut.in > sanOut29
slim selAndNeut.in > sanOut30
slim selAndNeut.in > sanOut31
slim selAndNeut.in > sanOut32
slim selAndNeut.in > sanOut33
slim selAndNeut.in > sanOut34
slim selAndNeut.in > sanOut35
slim selAndNeut.in > sanOut36
slim selAndNeut.in > sanOut37
slim selAndNeut.in > sanOut38
slim selAndNeut.in > sanOut39
slim selAndNeut.in > sanOut40
slim selAndNeut.in > sanOut41
slim selAndNeut.in > sanOut42
slim selAndNeut.in > sanOut43
slim selAndNeut.in > sanOut44
slim selAndNeut.in > sanOut45
slim selAndNeut.in > sanOut46
slim selAndNeut.in > sanOut47
slim selAndNeut.in > sanOut48
slim selAndNeut.in > sanOut49
slim selAndNeut.in > sanOut50
